name: pytest, dep scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  run_test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: check source code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: run snyk sast
        uses: snyk/actions/python@master
        with:
          command: test
          args: --severity-threshold=high --policy-path=.synk --python-version=3.12 --skip-unresolved --file=requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: run snyk sca
        uses: snyk/actions/python@master
        with:
          command: code test
          args: --severity-threshold=high --policy-path=.synk --python-version=3.12 --skip-unresolved --file=requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: configure aws credentials with ocid
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION_NAME }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }} # iam role for github actions
          role-session-name: GitHubActions-Build-Test-${{ github.run_id }}

      - name: test aws access
        run: |
          aws sts get-caller-identity
          echo "✅ oidc authentication successful"

      # pytest
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run pytest
        run: pytest
        # env:
        #   PYTEST_RUN: true
